#!/usr/bin/env bash

set -o nounset
set -o pipefail
# set -o xtrace

# Set magic variables for current file & dir
__dir=`dirname "$(readlink -f "$0")"`
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__bin="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# http://www.tldp.org/LDP/abs/html/exitcodes.html
# User-defined exit codes range 64 - 113 (in addition to 0, for success)
readonly SUCCESS=0
readonly E_NOT_ENOUGH_PRIVILEGES=113

# Constant variables
readonly PODMAN_CLI='podman'
readonly DOCKER_CLI='docker'

# Variables
build=false
force=false
exec=false
unset start
is_sudo=false
CONTAINER_ALIAS=${CONTAINER_ALIAS:-${PODMAN_CLI}}

# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash/39398359#39398359
# As long as there is at least one more argument, keep looping
while [[ $# -gt 0 ]]; do
    key="$1"
    case "${key}" in
        # This is a flag type option. Will catch either -b or --build
        -b|--build)
        build=true
        ;;
        # This is a flag type option. Will catch either -f or --force
        -f|--force)
        force=true
        ;;
        # This is a flag type option. Will catch either -d or --docker
        -d|--docker)
        CONTAINER_ALIAS="${DOCKER_CLI}"
        ;;
        # This is an arg value type option. Will catch -e value or --exec value
        -e|--exec)
        exec=true
        shift # past the key and to the value
        command="$1"
        ;;
        # This is an arg=value type option. Will catch -e=value or --exec=value
        -e=*|--exec=*)
        # No need to shift here since the value is part of the same string
        exec=true
        command="${key#*=}"
        ;;
        *)
        # Do whatever you want with extra arguments
        echo "Unknown argument '${key}'"
        ;;
    esac
    shift
done

# Set cloudbox environment
export CLOUDBOX_USER='cloudbox'
export CLOUDBOX_HOME="/home/${CLOUDBOX_USER}"
export CLOUDBOX_SSH="${CLOUDBOX_HOME}/.ssh"
export CLOUDBOX_HOST_SSH="${CLOUDBOX_HOME}/host_ssh"
export CLOUDBOX_WORKDIR="${CLOUDBOX_HOME}/Projects"
export CLOUDBOX_NAME='cloudbox'
export CLOUDBOX_VERSION='0.2.3'

VOLUME_NAME=${CLOUDBOX_USER}'_home'
DOCKER_TAG='local'/${CLOUDBOX_NAME}:${CLOUDBOX_VERSION}

# Functions

local_workdirs () {
    # Create local working directories and files
    if  [ "${is_sudo:-}" = "false" ]; then
        mkdir -p ${LOCAL_WORKDIR}
        mkdir -p ${LOCAL_SSH}
    else
        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_WORKDIR}
        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_SSH}
    fi
}

container_build () {
    # Build cloudbox image
    local args
    pushd ${__dir}
    args=''
    if  [ "${CONTAINER_ALIAS}" = "${PODMAN_CLI}" ]; then
        args+=('--layers')
    fi
    args+=('--force-rm=true'
        '--rm=true'
        "--build-arg=\"CLOUDBOX_USER=${CLOUDBOX_USER}\""
        "--build-arg=\"CLOUDBOX_SSH=${CLOUDBOX_SSH}\""
        "--build-arg=\"CLOUDBOX_HOST_SSH=${CLOUDBOX_HOST_SSH}\""
        "--build-arg=\"CLOUDBOX_WORKDIR=${CLOUDBOX_WORKDIR}\""
        "--build-arg=\"CLOUDBOX_NAME=${CLOUDBOX_NAME}\""
        "--build-arg=\"CLOUDBOX_VERSION=${CLOUDBOX_VERSION}\""
        "--build-arg=\"BUILD_DATE=$(date --utc +\"%FT%TZ\")\"")
    [ "${force:-}" = "true" ] && args+=('--no-cache')
    args+=("--tag='"${DOCKER_TAG}"'" '.')
    eval ${CONTAINER_ALIAS} build ${args[@]}
    popd
}

container_run () {
    # Run cloudbox container
    local args
    if [ "${exec:-}" = "true" ]; then
        args=('--detach')
    else
        args=('--interactive' '--tty' '--rm=true')
    fi

    local suffix=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 3`
    args+=("--hostname ${CONTAINER_ALIAS}-${suffix}")

    if  [ "${CONTAINER_ALIAS}" = "${DOCKER_CLI}" ]; then
        args+=("--mount type=bind,source=\"${LOCAL_SSH}\",target=\"${CLOUDBOX_HOST_SSH}\",ro=true"
            "--mount type=bind,source=\"${LOCAL_WORKDIR}\",target=\"${CLOUDBOX_WORKDIR}\"")
    else
        args+=("--mount type=bind,source=\"${LOCAL_SSH}\",target=\"${CLOUDBOX_HOST_SSH}\",relabel=shared,ro=true"
            "--mount type=bind,source=\"${LOCAL_WORKDIR}\",target=\"${CLOUDBOX_WORKDIR}\",relabel=shared"
            '--userns=keep-id')
    fi
    args+=("--mount type=volume,source=\"${VOLUME_NAME}\",target=\"${CLOUDBOX_HOME}\"")

    if [ "${PWD:0:${#LOCAL_WORKDIR}}" = "${LOCAL_WORKDIR}" ]; then
        subfolder=${PWD#${LOCAL_WORKDIR}/}
        if [ "${subfolder}" != "${LOCAL_WORKDIR}" ]; then
          args+=("--workdir \"${CLOUDBOX_WORKDIR}/${subfolder}\"")
        fi
    fi

    if [ "${exec:-}" = "true" ]; then
        args+=("--name ${CLOUDBOX_NAME}")
        args+=("${DOCKER_TAG}" 'tail -f /dev/null')
    else
        args+=("${DOCKER_TAG}" '/bin/bash')
    fi

    eval ${CONTAINER_ALIAS} run ${args[@]}
}

container_exec () {
    local args
    args=('--interactive' '--tty')
    args+=("${CLOUDBOX_NAME}" "${command}")

    eval ${CONTAINER_ALIAS} exec ${args[@]}
}

# Script prerequisites

# Check privileges
if [ $UID -eq 0 ]; then
    is_sudo=true
fi

if  [ "${CONTAINER_ALIAS}" = "${DOCKER_CLI}" ]; then
    user_in_docker=$(id --name --groups --zero "${USER:-${USERNAME:-${LOGNAME}}}" | grep -c --null-data --line-regexp --fixed-strings "${DOCKER_CLI}" || [[ $? == 1 ]])
    if ! ([ "${is_sudo:-}" = "true" ] || [ "${user_in_docker}" = "1" ]); then
        echo "use: sudo ${0##*/}"
        exit ${E_NOT_ENOUGH_PRIVILEGES}
    fi
fi

# Set local environment
if [ "${is_sudo:-}" = "false" ]; then
    LOCAL_HOME=${HOME}
else
    LOCAL_HOME="$(getent passwd ${SUDO_USER} | cut -d: -f6)"
fi
LOCAL_SSH="${LOCAL_HOME}/.ssh"
LOCAL_WORKDIR="${LOCAL_HOME}/Projects"

# Check for running container
if [ "${exec:-}" = "true" ]; then
    if ${CONTAINER_ALIAS} start ${CLOUDBOX_NAME} 2>/dev/null; then
        start=false
    else
        start=true
    fi
fi

# Script main

if [ "${start:-}" != "false" ]; then
    local_workdirs
fi

if [ "${build:-}" = "true" ]; then
    container_build
fi

if [ "${start:-}" = "true" ] || [ "${exec:-}" = "false" ]; then
    container_run
fi

if [ "${exec:-}" = "true" ]; then
    container_exec
fi